module.exports = {
  preset: 'react-native',
  cacheDirectory: '<rootDir>/dist/jest/cache',
  coverageDirectory: '<rootDir>/dist/jest/coverage',
  setupFilesAfterEnv: ['<rootDir>/jest.setup.js'],
  moduleFileExtensions: [
    'ts',
    'tsx',
    'js',
  ],
  transformIgnorePatterns: [
    'node_modules/(?!(react-native|@react-native|react-native-svg|@eva-design|@kittsune)/)',
  ],
  moduleNameMapper: {
    '^@kittsune/components/(.*)$': '<rootDir>/src/components/$1',
    '^@kittsune/components$': '<rootDir>/src/components',
    '^@kittsune/eva-icons/(.*)$': '<rootDir>/src/eva-icons/$1',
    '^@kittsune/eva-icons$': '<rootDir>/src/eva-icons',
    '^@kittsune/metro-config/(.*)$': '<rootDir>/src/metro-config/$1',
    '^@kittsune/metro-config$': '<rootDir>/src/metro-config',
    '^@kittsune/processor/(.*)$': '<rootDir>/src/processor/$1',
    '^@kittsune/processor$': '<rootDir>/src/processor',
    '^@kittsune/eva/(.*)$': '<rootDir>/src/eva/$1',
    '^@kittsune/eva$': '<rootDir>/src/eva',
    '^@kittsune/material/(.*)$': '<rootDir>/src/material/$1',
    '^@kittsune/material$': '<rootDir>/src/material',
    '^@kittsune/date-fns/(.*)$': '<rootDir>/src/date-fns/$1',
    '^@kittsune/date-fns$': '<rootDir>/src/date-fns',
    '^@kittsune/moment/(.*)$': '<rootDir>/src/moment/$1',
    '^@kittsune/moment$': '<rootDir>/src/moment',
    '^@kittsune/core/(.*)$': '<rootDir>/src/core/$1',
    '^@kittsune/core$': '<rootDir>/src/core',
    '^@kittsune/mapping-base/(.*)$': '<rootDir>/src/mapping-base/$1',
    '^@kittsune/mapping-base$': '<rootDir>/src/mapping-base',
  },
  modulePathIgnorePatterns: [
    '<rootDir>/src/showcases/',
    '<rootDir>/src/template-js/',
    '<rootDir>/src/template-ts/',
    '/lib/',
  ],
  testPathIgnorePatterns: [
    '<rootDir>/node_modules',
    '<rootDir>/dist',
    '<rootDir>/docs',
    '/lib/',
  ],
};
