module.exports = {
  preset: 'react-native',
  cacheDirectory: '<rootDir>/dist/jest/cache',
  coverageDirectory: '<rootDir>/dist/jest/coverage',
  moduleFileExtensions: [
    'ts',
    'tsx',
    'js',
  ],
  moduleNameMapper: {
    '^@kitsuine/components/(.*)$': '<rootDir>/src/components/$1',
    '^@kitsuine/components$': '<rootDir>/src/components',
    '^@kitsuine/eva-icons/(.*)$': '<rootDir>/src/eva-icons/$1',
    '^@kitsuine/eva-icons$': '<rootDir>/src/eva-icons',
    '^@kitsuine/metro-config/(.*)$': '<rootDir>/src/metro-config/$1',
    '^@kitsuine/metro-config$': '<rootDir>/src/metro-config',
    '^@kitsuine/processor/(.*)$': '<rootDir>/src/processor/$1',
    '^@kitsuine/processor$': '<rootDir>/src/processor',
    '^@kitsuine/eva/(.*)$': '<rootDir>/src/eva/$1',
    '^@kitsuine/eva$': '<rootDir>/src/eva',
    '^@kitsuine/material/(.*)$': '<rootDir>/src/material/$1',
    '^@kitsuine/material$': '<rootDir>/src/material',
    '^@kitsuine/date-fns/(.*)$': '<rootDir>/src/date-fns/$1',
    '^@kitsuine/date-fns$': '<rootDir>/src/date-fns',
    '^@kitsuine/moment/(.*)$': '<rootDir>/src/moment/$1',
    '^@kitsuine/moment$': '<rootDir>/src/moment',
  },
  modulePathIgnorePatterns: [
    '<rootDir>/src/showcases/',
    '<rootDir>/src/template-js/',
    '<rootDir>/src/template-ts/',
  ],
  testPathIgnorePatterns: [
    '<rootDir>/node_modules',
    '<rootDir>/dist',
    '<rootDir>/docs',
  ],
};
